from .Students import Students
from .Teachers import Teachers
from .Courses import Courses
from .Sections import Sections
from .Departments import Departments
from .Subjects import Subjects
from .Schedules import Schedules
from .Enrollments import Enrollments
from .EnrollmentDetails import EnrollmentDetails
from .Requirements import Requirements
from .StudentRequirements import StudentRequirements
from .Payments import Payments
from .Grades import Grades